#!/usr/bin/env python
"""
Utility script to verify the configured SMTP credentials by sending a test email.

The script reads SMTP settings from environment variables (ideally loaded from `.env`)
and sends a simple plaintext message to the recipient specified via CLI.

Usage:
    python scripts/test_smtp.py --to someone@example.com [--subject "Subject"] [--body "Message"]
"""

from __future__ import annotations

import argparse
import os
import smtplib
import sys
from email.message import EmailMessage

from dotenv import load_dotenv


def load_settings() -> dict[str, str]:
    """Load SMTP settings from environment variables and validate them."""
    load_dotenv()
    settings = {
        "server": os.getenv("SMTP_SERVER"),
        "port": os.getenv("SMTP_PORT"),
        "username": os.getenv("SMTP_USERNAME"),
        "password": os.getenv("SMTP_PASSWORD"),
        "from_email": os.getenv("FROM_EMAIL"),
        "use_tls": os.getenv("SMTP_USE_TLS"),
        "use_ssl": os.getenv("SMTP_USE_SSL"),
    }

    missing = [key for key, value in settings.items() if key in {"server", "port", "username", "password", "from_email"} and not value]
    if missing:
        raise SystemExit(f"Missing SMTP settings in environment: {', '.join(missing)}")

    try:
        settings["port"] = int(settings["port"])
    except ValueError as exc:
        raise SystemExit("SMTP_PORT must be an integer") from exc

    return settings


def determine_transport(settings: dict[str, str]) -> str:
    """Decide whether to use SSL or TLS based on env flags and port."""
    use_ssl = settings.get("use_ssl")
    use_tls = settings.get("use_tls")

    if use_ssl is not None:
        return "ssl" if use_ssl.lower() in {"1", "true", "yes"} else "tls"
    if use_tls is not None:
        return "tls" if use_tls.lower() in {"1", "true", "yes"} else "ssl"

    # Default heuristic: port 465 => SSL, otherwise TLS
    return "ssl" if settings["port"] == 465 else "tls"


def send_test_email(settings: dict[str, str], recipient: str, subject: str, body: str) -> None:
    """Compose and send the email using the appropriate transport."""
    message = EmailMessage()
    message["From"] = settings["from_email"]
    message["To"] = recipient
    message["Subject"] = subject
    message.set_content(body)

    transport = determine_transport(settings)

    try:
        if transport == "ssl":
            with smtplib.SMTP_SSL(settings["server"], settings["port"]) as smtp:
                smtp.login(settings["username"], settings["password"])
                smtp.send_message(message)
        else:
            with smtplib.SMTP(settings["server"], settings["port"]) as smtp:
                smtp.starttls()
                smtp.login(settings["username"], settings["password"])
                smtp.send_message(message)
    except Exception as exc:  # noqa: BLE001 - we want to capture any SMTP failure.
        raise SystemExit(f"SMTP send failed: {exc}") from exc


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description="Send a test email using current SMTP settings.")
    parser.add_argument("--to", required=True, help="Recipient email address for the test message.")
    parser.add_argument("--subject", default="SMTP Connectivity Test", help="Subject line for the test email.")
    parser.add_argument(
        "--body",
        default="This is a test email generated by scripts/test_smtp.py to verify SMTP connectivity.",
        help="Body content for the test email.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> None:
    args = parse_args(argv)
    settings = load_settings()
    send_test_email(settings, args.to, args.subject, args.body)
    print(f"Test email sent to {args.to} via {settings['server']}:{settings['port']}", file=sys.stdout)


if __name__ == "__main__":
    main(sys.argv[1:])
